(()=>{
const $=id=>document.getElementById(id),gate=$('regGate');if(!gate)return;
const tabs=gate.querySelector('.reg-tabs');tabs.classList.add('has-team');
const teamTab=document.createElement('button');teamTab.type='button';teamTab.dataset.teamTab='true';teamTab.textContent='研究团队';tabs.appendChild(teamTab);
const panel=gate.querySelector('.reg-panel'),teamView=document.createElement('div');teamView.className='reg-view';teamView.dataset.teamView='true';teamView.innerHTML=`<div class="research-auth-badge">● 研究管理安全入口</div><h2>研究团队登录</h2><p class="reg-muted">仅限经授权的研究团队成员访问注册审核和研究管理后台。</p><form class="reg-form" id="researchTeamLogin"><label>团队账号<input id="researchTeamUser" autocomplete="username" placeholder="请输入团队账号"></label><label>密码<input id="researchTeamPassword" type="password" autocomplete="current-password" placeholder="请输入密码"></label><button class="reg-primary full">进入研究后台</button></form><div class="reg-error" id="researchTeamError"></div><div class="reg-note"><b>原型演示账号</b><br>账号：research_admin<br>密码：MIED2026<br><span class="reg-muted">正式部署时应替换为服务器认证、分角色权限与操作审计。</span></div>`;panel.appendChild(teamView);
function selectTeam(){gate.querySelectorAll('.reg-tabs button').forEach(x=>x.classList.toggle('active',x===teamTab));gate.querySelectorAll('.reg-view').forEach(x=>x.classList.remove('active'));teamView.classList.add('active');$('researchTeamUser').focus()}
teamTab.onclick=selectTeam;gate.querySelectorAll('.reg-tabs button:not([data-team-tab])').forEach(button=>button.addEventListener('click',()=>teamView.classList.remove('active')));
function registrationData(){try{return JSON.parse(localStorage.getItem('mied_registration_v19')||'{"applications":[]}')}catch(e){return{applications:[]}}}
function pendingCount(){return registrationData().applications.filter(x=>x.status==='pending').length}
function updateQueueBanner(){const dashboard=$('admin-dashboard');if(!dashboard)return;let banner=$('researchQueueBanner');if(!banner){banner=document.createElement('div');banner.id='researchQueueBanner';banner.className='research-queue-banner';const head=dashboard.querySelector('.admin-page-head');head?.insertAdjacentElement('afterend',banner)}const count=pendingCount();banner.innerHTML=`<div><b>${count?`有 ${count} 条注册申请等待审核`:'当前没有待审核注册申请'}</b><span>核对基本资料、初始量表与知情同意记录，批准后系统将开通参与者账号。</span></div><button type="button" id="openRegistrationReview">${count?'立即审核':'查看审核记录'}</button>`;$('openRegistrationReview').onclick=openReview}
function openReview(){const button=document.querySelector('[data-admin-page="applications"]');if(button)button.click()}
function enterResearchAdmin(){gate.classList.add('hidden');document.body.classList.remove('reg-lock');$('launcher')?.classList.add('hidden');if(typeof enterAdmin==='function')enterAdmin();updateQueueBanner();setTimeout(openReview,0)}
$('researchTeamLogin').onsubmit=e=>{e.preventDefault();const user=$('researchTeamUser').value.trim(),password=$('researchTeamPassword').value;if(user==='research_admin'&&password==='MIED2026'){sessionStorage.setItem('mied_research_auth','yes');$('researchTeamError').textContent='';enterResearchAdmin()}else $('researchTeamError').textContent='团队账号或密码不正确。'};
function returnToGate(){if(typeof leaveAdmin==='function')leaveAdmin();$('launcher')?.classList.add('hidden');$('appWrap')?.classList.add('hidden');gate.classList.remove('hidden');document.body.classList.add('reg-lock');sessionStorage.removeItem('mied_research_auth');selectTeam()}
if($('adminLogout'))$('adminLogout').onclick=returnToGate;if($('adminBackHome')){$('adminBackHome').textContent='返回登录页';$('adminBackHome').onclick=returnToGate}
const oldAdmin=$('openAdmin');if(oldAdmin)oldAdmin.onclick=()=>{gate.classList.remove('hidden');$('launcher')?.classList.add('hidden');document.body.classList.add('reg-lock');selectTeam()};
updateQueueBanner();document.documentElement.dataset.researchTeamVersion='v20';
})();
