(()=>{
const $=id=>document.getElementById(id),GROUP_KEY='mied_participant_groups_v22',PRACTICE_KEY='mied_practice_access_v21',escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),toJson=x=>{try{return JSON.stringify(x??{})}catch(e){return'{}'}};
const config={
 daily_assessment:{label:'每日量表',family:'测评量表得分',hint:'按日期记录的每日量表得分',fields:[['participant_id','参与者编号'],['group','参与者分组'],['assessment_date','测评日期'],['scale_id','量表编号'],['scale_name','量表名称'],['total_score','总分/均分'],['normalized_score','标准化分数'],['dimension_scores','维度得分'],['completed_at','提交时间']]},
 wave_assessment:{label:'T0–T3测评',family:'测评量表得分',hint:'T0、T1、T2、T3研究时间点',fields:[['participant_id','参与者编号'],['group','参与者分组'],['wave','测评时间点'],['wave_name','时间点名称'],['scale_id','量表编号'],['scale_name','量表名称'],['total_score','总分/均分'],['normalized_score','标准化分数'],['dimension_scores','维度得分'],['completed_at','提交时间']]},
 checkin_task:{label:'打卡任务',family:'练习用户使用日志',hint:'每日打卡与研究团队推荐练习任务',fields:[['participant_id','参与者编号'],['group','参与者分组'],['task_type','任务类型'],['task_name','任务名称'],['task_date','任务日期'],['status','完成状态'],['minutes','使用分钟'],['heart_awarded','获得心灯'],['has_form_record','含填写记录'],['checkin_done','完成内容'],['checkin_feeling','当前状态'],['checkin_tomorrow','明日行动'],['completed_at','完成时间']]},
 voluntary_practice:{label:'自愿练习',family:'练习用户使用日志',hint:'参与者自主选择、非推荐任务的练习',fields:[['participant_id','参与者编号'],['group','参与者分组'],['practice_name','练习名称'],['practice_date','使用日期'],['status','完成状态'],['minutes','使用分钟'],['heart_awarded','获得心灯'],['has_form_record','含填写记录'],['completed_at','完成时间']]}
};
let active='daily_assessment';
function groupStore(){try{const x=JSON.parse(localStorage.getItem(GROUP_KEY)||'{}');return{groups:x.groups||['待分组','演示组'],assignments:x.assignments||{}}}catch(e){return{groups:['待分组','演示组'],assignments:{}}}}
function practiceUsage(){try{return JSON.parse(localStorage.getItem(PRACTICE_KEY)||'{"usage":[]}').usage||[]}catch(e){return[]}}
function participantGroups(){const map={};try{allParticipants().forEach(x=>map[x.id]=x.group)}catch(e){}return map}
function groupOf(pid){const store=groupStore();return store.assignments[pid]||participantGroups()[pid]||'待分组'}
function dimensions(record){return Object.fromEntries(Object.entries(record.scores||{}).filter(([key,value])=>key!=='_meta'&&typeof value==='number'))}
function assessmentRow(record,wave,date){const meta=record.scores?._meta||record.meta||{},pid=record.participantId||record.participant_id||'MIED-001';return{participant_id:pid,group:groupOf(pid),wave:wave||record.wave||'',wave_name:record.waveName||record.wave_name||'',assessment_date:date||String(record.completedAt||record.completed_at||'').slice(0,10),scale_id:record.scaleKey||record.scale_id||record.scaleId||'',scale_name:record.scaleName||record.scale_name||'',total_score:meta.overall??record.total_score??record.totalScore??'',normalized_score:meta.normalized??record.normalized_score??'',dimension_scores:toJson(record.dimension_scores||dimensions(record)),completed_at:record.completedAt||record.completed_at||''}}
function dailyAssessmentRows(){const rows=[],seen=new Set(),add=(record,date)=>{if(!record)return;const row=assessmentRow(record,'DAILY',date),id=[row.participant_id,row.assessment_date,row.scale_id,row.completed_at].join('|');if(!seen.has(id)){seen.add(id);rows.push(row)}};(state.assessmentRecords||[]).filter(x=>x.wave==='DAILY').forEach(x=>add(x));[...(state.dailyAssessmentRecords||[]),...(state.dailyScaleRecords||[])].forEach(x=>add(x,x.date));Object.entries(state.daily||{}).forEach(([date,d])=>[...(d.assessmentRecords||[]),...(d.scaleRecords||[]),...(d.assessments||[])].forEach(x=>add(x,date)));return rows}
function waveAssessmentRows(){return(state.assessmentRecords||[]).filter(x=>/^T[0-3]$/.test(x.wave)).map(x=>assessmentRow(x,x.wave))}
function checkinRows(){const rows=[],pid='MIED-001';Object.entries(state.checkins||{}).forEach(([date,x])=>rows.push({participant_id:pid,group:groupOf(pid),task_type:'每日打卡',task_name:'每日打卡任务',task_date:date,status:'已完成',minutes:0,heart_awarded:8,has_form_record:'是',checkin_done:x.done||'',checkin_feeling:x.feeling||'',checkin_tomorrow:x.tomorrow||'',completed_at:x.completedAt||date}));practiceUsage().filter(x=>x.status==='completed'&&x.recommended).forEach(x=>rows.push({participant_id:x.participantId,group:groupOf(x.participantId),task_type:'推荐练习任务',task_name:x.title,task_date:String(x.usedAt||'').slice(0,10),status:'已完成',minutes:Number(x.minutes)||0,heart_awarded:Number(x.awarded)||0,has_form_record:x.hasForm?'是':'否',checkin_done:'',checkin_feeling:'',checkin_tomorrow:'',completed_at:x.usedAt||''}));return rows.sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at))}
function voluntaryRows(){return practiceUsage().filter(x=>x.status==='completed'&&!x.recommended).map(x=>({participant_id:x.participantId,group:groupOf(x.participantId),practice_name:x.title,practice_date:String(x.usedAt||'').slice(0,10),status:'已完成',minutes:Number(x.minutes)||0,heart_awarded:Number(x.awarded)||0,has_form_record:x.hasForm?'是':'否',completed_at:x.usedAt||''})).sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at))}
function rawRows(){return active==='daily_assessment'?dailyAssessmentRows():active==='wave_assessment'?waveAssessmentRows():active==='checkin_task'?checkinRows():voluntaryRows()}
function filteredRows(){const group=$('splitExportGroup')?.value||'all';return rawRows().filter(x=>group==='all'||x.group===group)}
function selectedFields(){return[...document.querySelectorAll('#splitExportFields [data-split-field]:checked')].map(x=>x.dataset.splitField)}
function forceMenuName(){document.querySelectorAll('[data-admin-page="data"]').forEach(item=>{const icon=item.querySelector('i');if(icon)icon.textContent='出';[...item.childNodes].filter(n=>n.nodeType===3).forEach(n=>n.textContent='数据导出')});if(typeof adminTitles!=='undefined')adminTitles.data='数据导出'}
function build(){const page=$('admin-data');if(!page)return;forceMenuName();page.querySelector('.admin-page-head span').textContent='按分组与数据类型';page.querySelector('.admin-page-head h2').textContent='数据导出';page.querySelector('.admin-page-head p').textContent='分别选择每日量表、T0–T3测评、打卡任务或自愿练习，按参与者分组单独导出。';let box=$('exportWorkbench');if(!box){box=document.createElement('div');box.id='exportWorkbench';box.className='export-workbench';page.appendChild(box)}[...page.children].filter(x=>!x.classList.contains('admin-page-head')&&x!==box).forEach(x=>x.style.display='none');box.innerHTML=`<div class="export-toolbar"><div class="export-toolbar-left"><label>选择参与者分组<select id="splitExportGroup"></select></label></div><span class="panel-tag">每次仅导出当前数据类型</span></div><div class="export-dataset-tabs split-four">${Object.entries(config).map(([key,x])=>`<button data-split-dataset="${key}"><span>${x.label}</span><small>${x.family}</small></button>`).join('')}</div><div class="export-summary" id="splitExportSummary"></div><section class="export-fields-panel"><div class="export-fields-head"><div><span class="export-split-kicker" id="splitFamily"></span><h3 id="splitDatasetTitle"></h3><span class="reg-muted" id="splitDatasetHint"></span></div><div><button id="splitSelectAll">全选</button><button id="splitClearAll">清空</button></div></div><div class="export-field-grid" id="splitExportFields"></div></section><section class="export-preview-panel"><div class="export-preview-head"><div><h3>当前数据预览</h3><span>最多显示前20条；导出包含当前分组下的全部记录。</span></div><span id="splitPreviewCount"></span></div><div class="export-preview-scroll" id="splitPreview"></div></section><div class="export-actions-v23"><p id="splitExportHint"></p><button id="splitDownload">单独导出当前数据 CSV</button></div>`;$('splitExportGroup').onchange=renderData;$('splitSelectAll').onclick=()=>{document.querySelectorAll('[data-split-field]').forEach(x=>x.checked=true);renderPreview()};$('splitClearAll').onclick=()=>{document.querySelectorAll('[data-split-field]').forEach(x=>x.checked=false);renderPreview()};$('splitDownload').onclick=download;box.querySelectorAll('[data-split-dataset]').forEach(x=>x.onclick=()=>{active=x.dataset.splitDataset;renderData()});renderGroups();renderData()}
function renderGroups(){const select=$('splitExportGroup'),current=select?.value||'all',available=new Set([...groupStore().groups,...Object.keys(groupStore().assignments).map(pid=>groupOf(pid)),...rawRows().map(x=>x.group)]);select.innerHTML='<option value="all">全部分组</option>'+[...available].filter(Boolean).map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');select.value=current==='all'||available.has(current)?current:'all'}
function renderData(){if(!$('splitExportFields'))return;renderGroups();document.querySelectorAll('[data-split-dataset]').forEach(x=>x.classList.toggle('active',x.dataset.splitDataset===active));const current=config[active];$('splitFamily').textContent=current.family;$('splitDatasetTitle').textContent=current.label;$('splitDatasetHint').textContent=current.hint;$('splitExportFields').innerHTML=current.fields.map(([key,label])=>`<label class="export-field-option"><input type="checkbox" data-split-field="${key}" checked><span><b>${escapeHtml(label)}</b><span>${key}</span></span></label>`).join('');document.querySelectorAll('[data-split-field]').forEach(x=>x.onchange=renderPreview);const rows=filteredRows(),participants=new Set(rows.map(x=>x.participant_id)),groupsCount=new Set(rows.map(x=>x.group)),amount=active.includes('assessment')?new Set(rows.map(x=>x.wave||x.assessment_date)).size:rows.reduce((sum,x)=>sum+(Number(x.minutes)||0),0);$('splitExportSummary').innerHTML=[[rows.length,'当前记录'],[participants.size,'参与者'],[groupsCount.size,'涉及分组'],[amount,active.includes('assessment')?'日期/时间点':'累计分钟']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');renderPreview()}
function renderPreview(){const rows=filteredRows(),selected=selectedFields(),labels=Object.fromEntries(config[active].fields),group=$('splitExportGroup').selectedOptions[0]?.textContent||'全部分组';$('splitPreviewCount').textContent=`${rows.length} 条 · ${selected.length} 个字段`;$('splitExportHint').textContent=`即将单独导出：${group} / ${config[active].family} / ${config[active].label}`;if(!selected.length){$('splitPreview').innerHTML='<div class="export-preview-empty">请至少勾选一个字段。</div>';return}if(!rows.length){$('splitPreview').innerHTML=`<div class="export-preview-empty">当前分组暂无“${config[active].label}”真实记录。</div>`;return}$('splitPreview').innerHTML=`<table class="export-preview-table"><thead><tr>${selected.map(x=>`<th>${escapeHtml(labels[x])}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,20).map(row=>`<tr>${selected.map(x=>`<td title="${escapeHtml(row[x])}">${escapeHtml(row[x])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function csv(value){return'"'+String(value??'').replace(/"/g,'""')+'"'}function download(){const rows=filteredRows(),selected=selectedFields();if(!selected.length)return alert('请至少勾选一个字段。');if(!rows.length)return alert(`当前分组没有可导出的“${config[active].label}”记录。`);const labels=Object.fromEntries(config[active].fields),content='\ufeff'+[selected.map(x=>labels[x]),...rows.map(row=>selected.map(x=>row[x]))].map(row=>row.map(csv).join(',')).join('\r\n'),group=$('splitExportGroup').value==='all'?'all_groups':$('splitExportGroup').value;downloadFile(`mied_${active}_${group}_${new Date().toISOString().slice(0,10)}.csv`,content,'text/csv;charset=utf-8');addAdminActivity(`单独导出${config[active].label}：${rows.length}条`);saveAdmin()}
forceMenuName();const oldRenderAdminData=renderAdminData;renderAdminData=function(){try{oldRenderAdminData()}catch(e){}build()};const oldRenderAdminPage=renderAdminPage;renderAdminPage=function(id){oldRenderAdminPage(id);if(id==='data')build()};build();document.documentElement.dataset.splitDataExportVersion='v24';
})();
