(()=>{
const $=id=>document.getElementById(id),fieldState={};
function initState(key){if(!fieldState[key])fieldState[key]=Object.fromEntries(defs[key].fields.map(([field])=>[field,true]));return fieldState[key]}
chosenFields=function(key){const state=initState(key);return defs[key].fields.map(([field])=>field).filter(field=>state[field]!==false)};
previewBlock=function(key){const rows=filtered(key),state=initState(key),labels=Object.fromEntries(defs[key].fields),allFields=defs[key].fields.map(([field])=>field),chosen=chosenFields(key);let table='<div class="export-preview-empty">当前分组暂无真实记录。</div>';if(rows.length)table=`<div class="credamo-grid-toolbar"><span class="credamo-grid-hint"><i></i>直接勾选表头，决定该列是否导出</span><div><button data-grid-all="${key}">全选列</button><button data-grid-clear="${key}">清空列</button></div></div><div class="credamo-grid-wrap"><table class="credamo-grid"><thead><tr>${allFields.map((field,index)=>`<th class="${state[field]===false?'excluded':''}"><label class="credamo-grid-label" title="${labels[field]} · ${field}"><input type="checkbox" data-grid-field="${key}" data-field="${field}" ${state[field]===false?'':'checked'}><b>${labels[field]}</b><small>▾</small></label></th>`).join('')}</tr></thead><tbody>${rows.slice(0,20).map(row=>`<tr>${allFields.map(field=>`<td class="${state[field]===false?'excluded':''}" title="${html(row[field])}">${html(row[field])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="grid-horizontal-tip">可左右滚动查看全部字段 · 预览前20条，实际导出全部记录</div>`;return`<article class="multi-preview-block" data-grid-block="${key}"><div class="multi-preview-title"><b>${defs[key].family} · ${defs[key].label}</b><span>${rows.length} 条记录 · <strong>${chosen.length}</strong> / ${allFields.length} 列导出</span></div>${table}</article>`}
function bindGrids(){document.querySelectorAll('[data-grid-field]').forEach(input=>input.onchange=()=>{initState(input.dataset.gridField)[input.dataset.field]=input.checked;renderPreviews();updateFooter()});document.querySelectorAll('[data-grid-all]').forEach(button=>button.onclick=()=>{Object.keys(initState(button.dataset.gridAll)).forEach(field=>fieldState[button.dataset.gridAll][field]=true);renderPreviews();updateFooter()});document.querySelectorAll('[data-grid-clear]').forEach(button=>button.onclick=()=>{Object.keys(initState(button.dataset.gridClear)).forEach(field=>fieldState[button.dataset.gridClear][field]=false);renderPreviews();updateFooter()})}
const oldRenderPreviews=renderPreviews;renderPreviews=function(){oldRenderPreviews();bindGrids()};
document.querySelectorAll('.multi-field-toggle,.multi-field-box').forEach(x=>x.remove());renderPreviews();updateFooter();document.documentElement.dataset.dataGridVersion='v26';
})();
