(()=>{
const KEY='mied_participant_groups_v22',$=id=>document.getElementById(id),safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{groups:Array.isArray(x.groups)&&x.groups.length?x.groups:['待分组','演示组','干预A组','干预B组'],assignments:x.assignments||{},applicationGroups:x.applicationGroups||{}}}catch(e){return{groups:['待分组','演示组','干预A组','干预B组'],assignments:{},applicationGroups:{}}}}
function write(x){localStorage.setItem(KEY,JSON.stringify(x))}function reg(){try{return JSON.parse(localStorage.getItem('mied_registration_v19')||'{"applications":[]}')}catch(e){return{applications:[]}}}function groupOf(pid,fallback='待分组'){return read().assignments[pid]||fallback||'待分组'}
function syncApproved(){const store=read();reg().applications.forEach(app=>{if(app.status==='approved'&&app.participantId){const group=store.applicationGroups[app.id]||app.group;if(group)store.assignments[app.participantId]=group}});write(store)}
const allParticipantsBeforeGroups=allParticipants;allParticipants=function(){syncApproved();return allParticipantsBeforeGroups().map(x=>({...x,group:groupOf(x.id,x.group)}))};
function organizeIntervention(){const page=$('admin-intervention');if(!page)return;let nav=$('interventionSubnav'),course=$('interventionCourseView'),practice=$('interventionPracticeView');if(!nav){nav=document.createElement('div');nav.id='interventionSubnav';nav.className='intervention-subnav';nav.innerHTML='<button data-intervention-sub="course">八周课程考勤</button><button data-intervention-sub="practice">练习权限与记录</button>';page.querySelector('.admin-page-head')?.insertAdjacentElement('afterend',nav);course=document.createElement('div');course.id='interventionCourseView';course.className='intervention-subview';practice=document.createElement('div');practice.id='interventionPracticeView';practice.className='intervention-subview';nav.insertAdjacentElement('afterend',course);course.insertAdjacentElement('afterend',practice);nav.querySelectorAll('button').forEach(x=>x.onclick=()=>switchIntervention(x.dataset.interventionSub))}const fixed=new Set(['interventionSubnav','interventionCourseView','interventionPracticeView']);[...page.children].filter(x=>!x.classList.contains('admin-page-head')&&!fixed.has(x.id)).forEach(x=>(x.id==='participantPracticeAccess'||x.id==='participantPracticeUsage'?practice:course).appendChild(x));switchIntervention(adminState.interventionSubpage||'course')}
function switchIntervention(kind){adminState.interventionSubpage=kind;saveAdmin();$('interventionSubnav')?.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.interventionSub===kind));$('interventionCourseView')?.classList.toggle('active',kind==='course');$('interventionPracticeView')?.classList.toggle('active',kind==='practice');const title=document.querySelector('#admin-intervention .admin-page-head h2'),copy=document.querySelector('#admin-intervention .admin-page-head p');if(title)title.textContent=kind==='course'?'八周课程考勤':'练习权限与使用记录';if(copy)copy.textContent=kind==='course'?'同步腾讯会议出勤、周完成情况与课程PPT。':'按参与者设置每项练习的使用权限，并查看练习时长、完成及填写记录。'}
const renderAdminInterventionBeforeSubpages=renderAdminIntervention;renderAdminIntervention=function(){renderAdminInterventionBeforeSubpages();organizeIntervention()};
function groupOptions(selected){return read().groups.map(g=>`<option value="${safe(g)}" ${g===selected?'selected':''}>${safe(g)}</option>`).join('')}
function ensureGroupModal(){if($('groupModalV22'))return;const modal=document.createElement('div');modal.id='groupModalV22';modal.className='group-modal-v22';modal.innerHTML=`<div class="group-modal-card"><h3>参与者分组管理</h3><p>新增或删除研究分组。删除分组后，组内申请与参与者将自动移入“待分组”。</p><div class="group-add-row"><input id="newGroupName" maxlength="24" placeholder="输入新组名"><button id="addGroupV22">新增分组</button></div><div class="group-list-v22" id="groupListV22"></div><div class="group-modal-actions"><button id="closeGroupV22">完成</button></div></div>`;document.body.appendChild(modal);$('addGroupV22').onclick=()=>{const name=$('newGroupName').value.trim(),store=read();if(!name)return;if(store.groups.includes(name)){alert('该组名已经存在。');return}store.groups.push(name);write(store);$('newGroupName').value='';renderGroupManager();enhanceAllGroups()};$('closeGroupV22').onclick=()=>modal.classList.remove('open')}
function openGroupManager(){ensureGroupModal();renderGroupManager();$('groupModalV22').classList.add('open')}
function renderGroupManager(){const store=read(),apps=reg().applications;$('groupListV22').innerHTML=store.groups.map(g=>{const count=Object.values(store.assignments).filter(x=>x===g).length+Object.values(store.applicationGroups).filter(x=>x===g).length;return`<div class="group-row-v22"><div><b>${safe(g)}</b><span>${count} 名参与者/申请</span></div>${g==='待分组'?'':`<button data-delete-group="${safe(g)}">删除</button>`}</div>`}).join('');$('groupListV22').querySelectorAll('[data-delete-group]').forEach(x=>x.onclick=()=>{const name=x.dataset.deleteGroup;if(!confirm(`删除“${name}”并将组内人员移至“待分组”？`))return;const store=read();store.groups=store.groups.filter(g=>g!==name);Object.keys(store.assignments).forEach(k=>{if(store.assignments[k]===name)store.assignments[k]='待分组'});Object.keys(store.applicationGroups).forEach(k=>{if(store.applicationGroups[k]===name)store.applicationGroups[k]='待分组'});write(store);renderGroupManager();enhanceAllGroups()})}
function ensureParticipantGroupBar(){const page=$('admin-participants'),toolbar=page?.querySelector('.admin-toolbar');if(!page||$('participantGroupBar'))return;const bar=document.createElement('div');bar.id='participantGroupBar';bar.className='group-management-bar';bar.innerHTML=`<b>参与者分组</b><div><label>筛选分组 <select id="participantGroupFilter"><option value="all">全部分组</option></select></label><button id="manageGroupsParticipants">管理分组</button></div>`;(toolbar||page.querySelector('.admin-page-head')).insertAdjacentElement('afterend',bar);$('participantGroupFilter').onchange=filterParticipantRows;$('manageGroupsParticipants').onclick=openGroupManager}
function enhanceParticipantRows(){ensureParticipantGroupBar();const filter=$('participantGroupFilter'),store=read();if(filter){const selected=filter.value;filter.innerHTML='<option value="all">全部分组</option>'+store.groups.map(g=>`<option value="${safe(g)}">${safe(g)}</option>`).join('');filter.value=store.groups.includes(selected)||selected==='all'?selected:'all'}document.querySelectorAll('#participantTableBody tr').forEach(row=>{const pid=row.querySelector('td b')?.textContent.trim();if(!pid||!/^MIED-/.test(pid))return;const cell=row.querySelector('td'),fallback=cell.querySelector('span')?.textContent.trim(),selected=groupOf(pid,fallback);row.dataset.participantGroup=selected;let select=row.querySelector('.participant-group-select');if(!select){select=document.createElement('select');select.className='participant-group-select';cell.appendChild(select);select.onchange=()=>{const s=read();s.assignments[pid]=select.value;write(s);row.dataset.participantGroup=select.value;addAdminActivity(`${pid} 已调整至 ${select.value}`);saveAdmin();filterParticipantRows()}}select.innerHTML=groupOptions(selected);select.value=selected});filterParticipantRows()}
function filterParticipantRows(){const value=$('participantGroupFilter')?.value||'all';document.querySelectorAll('#participantTableBody tr[data-participant-group]').forEach(row=>row.style.display=value==='all'||row.dataset.participantGroup===value?'':'none')}
function ensureApplicationGroupBar(){const page=$('admin-applications'),head=page?.querySelector('.admin-page-head');if(!page||$('applicationGroupBar'))return;const bar=document.createElement('div');bar.id='applicationGroupBar';bar.className='group-management-bar';bar.innerHTML='<b>审核前分组</b><div><button id="manageGroupsApplications">管理分组</button></div>';head.insertAdjacentElement('afterend',bar);$('manageGroupsApplications').onclick=openGroupManager}
function enhanceApplicationRows(){ensureApplicationGroupBar();const data=reg(),store=read();document.querySelectorAll('#regApplicationBody tr').forEach(row=>{const appId=row.querySelector('td b')?.textContent.trim();const app=data.applications.find(x=>x.id===appId);if(!app)return;const cell=row.cells[1]||row.cells[0];let box=row.querySelector('.application-group-box');if(!box){box=document.createElement('label');box.className='application-group-box';box.innerHTML='<small>分配研究组</small><select class="application-group-select"></select>';cell.appendChild(box);box.querySelector('select').onchange=e=>{const s=read();s.applicationGroups[appId]=e.target.value;if(app.participantId)s.assignments[app.participantId]=e.target.value;write(s)}}const selected=store.applicationGroups[appId]||app.group||'待分组',select=box.querySelector('select');select.innerHTML=groupOptions(selected);select.value=selected})}
let enhancing=false;function enhanceAllGroups(){if(enhancing)return;enhancing=true;syncApproved();ensureGroupModal();enhanceParticipantRows();enhanceApplicationRows();organizeIntervention();enhancing=false}
const observer=new MutationObserver(mutations=>{if(mutations.some(m=>m.target.closest?.('#participantTableBody,#regApplicationBody,#admin-intervention')))setTimeout(enhanceAllGroups,0)});observer.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{const approve=e.target.closest?.('[data-approve]');if(approve){const id=approve.dataset.approve,set=read().applicationGroups[id]||'待分组';setTimeout(()=>{const data=reg(),app=data.applications.find(x=>x.id===id),store=read();if(app?.participantId){store.assignments[app.participantId]=set;write(store);enhanceAllGroups()}},80)}} ,true);
syncApproved();ensureGroupModal();organizeIntervention();enhanceAllGroups();document.documentElement.dataset.interventionGroupsVersion='v22';
})();
