(()=>{
const $=id=>document.getElementById(id),GROUP_KEY='mied_participant_groups_v22',PRACTICE_KEY='mied_practice_access_v21',safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),json=x=>{try{return JSON.stringify(x??{})}catch(e){return'{}'}};
const datasets={assessment:{label:'测评量表得分',description:'每日量表及 T0–T3 测评得分'},practice:{label:'练习用户使用日志',description:'打卡任务与自愿练习'}};
const fields={assessment:[['participant_id','参与者编号'],['group','参与者分组'],['assessment_type','测评类型'],['wave','时间点'],['assessment_date','测评日期'],['scale_id','量表编号'],['scale_name','量表名称'],['total_score','总分/均分'],['normalized_score','标准化分数'],['dimension_scores','维度得分'],['completed_at','提交时间']],practice:[['participant_id','参与者编号'],['group','参与者分组'],['log_type','日志分类'],['task_name','任务/练习名称'],['status','完成状态'],['practice_date','使用日期'],['minutes','使用分钟'],['recommended','是否推荐任务'],['heart_awarded','获得心灯'],['has_form_record','是否含填写记录'],['checkin_done','打卡：完成内容'],['checkin_feeling','打卡：当前状态'],['checkin_tomorrow','打卡：明日行动'],['used_at','使用时间']]};
let active='assessment';function groups(){try{const x=JSON.parse(localStorage.getItem(GROUP_KEY)||'{}');return{groups:x.groups||['待分组','演示组'],assignments:x.assignments||{}}}catch(e){return{groups:['待分组','演示组'],assignments:{}}}}function groupOf(pid,fallback='待分组'){return groups().assignments[pid]||fallback||'待分组'}function usage(){try{return JSON.parse(localStorage.getItem(PRACTICE_KEY)||'{"usage":[]}').usage||[]}catch(e){return[]}}
function participantMap(){const map={};try{allParticipants().forEach(x=>map[x.id]=x.group)}catch(e){}return map}
function dimensionScores(record){return Object.fromEntries(Object.entries(record.scores||{}).filter(([key,value])=>key!=='_meta'&&typeof value==='number'))}
function assessmentRows(){const rows=[],seen=new Set(),add=(r,type,wave,date)=>{if(!r)return;const id=[r.participantId||r.participant_id||'MIED-001',wave||r.wave,r.scaleKey||r.scale_id,r.completedAt||r.completed_at||date].join('|');if(seen.has(id))return;seen.add(id);const meta=r.scores?._meta||r.meta||{},pid=r.participantId||r.participant_id||'MIED-001';rows.push({participant_id:pid,group:groupOf(pid,participantMap()[pid]),assessment_type:type,wave:wave||r.wave||'',assessment_date:date||String(r.completedAt||r.completed_at||'').slice(0,10),scale_id:r.scaleKey||r.scale_id||r.scaleId||'',scale_name:r.scaleName||r.scale_name||'',total_score:meta.overall??r.total_score??r.totalScore??'',normalized_score:meta.normalized??r.normalized_score??'',dimension_scores:json(r.dimension_scores||dimensionScores(r)),completed_at:r.completedAt||r.completed_at||''})};(state.assessmentRecords||[]).forEach(r=>add(r,r.wave==='DAILY'?'每日量表':'研究时间点量表',r.wave));[...(state.dailyAssessmentRecords||[]),...(state.dailyScaleRecords||[])].forEach(r=>add(r,'每日量表','DAILY',r.date));Object.entries(state.daily||{}).forEach(([date,d])=>[...(d.assessmentRecords||[]),...(d.scaleRecords||[]),...(d.assessments||[])].forEach(r=>add(r,'每日量表','DAILY',date)));return rows.filter(r=>r.wave==='DAILY'||/^T[0-3]$/.test(r.wave))}
function practiceRows(){const map=participantMap(),rows=[];usage().filter(x=>x.status==='completed').forEach(x=>rows.push({participant_id:x.participantId,group:groupOf(x.participantId,map[x.participantId]),log_type:x.recommended?'打卡任务':'自愿练习',task_name:x.title,status:'已完成',practice_date:String(x.usedAt||'').slice(0,10),minutes:Number(x.minutes)||0,recommended:x.recommended?'是':'否',heart_awarded:Number(x.awarded)||0,has_form_record:x.hasForm?'是':'否',checkin_done:'',checkin_feeling:'',checkin_tomorrow:'',used_at:x.usedAt||''}));Object.entries(state.checkins||{}).forEach(([date,x])=>rows.push({participant_id:'MIED-001',group:groupOf('MIED-001',map['MIED-001']),log_type:'打卡任务',task_name:'每日打卡',status:'已完成',practice_date:date,minutes:0,recommended:'是',heart_awarded:8,has_form_record:'是',checkin_done:x.done||'',checkin_feeling:x.feeling||'',checkin_tomorrow:x.tomorrow||'',used_at:x.completedAt||date}));return rows.sort((a,b)=>new Date(b.used_at)-new Date(a.used_at))}
function rows(){const list=active==='assessment'?assessmentRows():practiceRows(),filter=$('exportGroupFilter')?.value||'all';return list.filter(x=>filter==='all'||x.group===filter)}
function selectedFields(){return[...document.querySelectorAll('[data-export-field]:checked')].map(x=>x.dataset.exportField)}
function buildPage(){const page=$('admin-data');if(!page||$('exportWorkbench'))return;page.querySelector('.admin-page-head span').textContent='研究数据';page.querySelector('.admin-page-head h2').textContent='数据导出';page.querySelector('.admin-page-head p').textContent='按分组筛选测评量表得分或练习使用日志，并在导出前选择字段和预览数据。';const oldButton=page.querySelector('.admin-page-head button');if(oldButton)oldButton.remove();[...page.children].filter(x=>!x.classList.contains('admin-page-head')).forEach(x=>x.style.display='none');const box=document.createElement('div');box.id='exportWorkbench';box.className='export-workbench';box.innerHTML=`<div class="export-toolbar"><div class="export-toolbar-left"><label>参与者分组<select id="exportGroupFilter"></select></label></div><span class="panel-tag">CSV · UTF-8</span></div><div class="export-dataset-tabs"><button data-export-dataset="assessment">测评量表得分<small>每日量表和 T0–T3</small></button><button data-export-dataset="practice">练习用户使用日志<small>打卡任务和自愿练习</small></button></div><div class="export-summary" id="exportSummary"></div><section class="export-fields-panel"><div class="export-fields-head"><div><h3>选择导出字段</h3><span class="reg-muted">取消勾选的字段不会进入预览或导出文件。</span></div><div><button id="selectAllExportFields">全选</button><button id="clearExportFields">清空</button></div></div><div class="export-field-grid" id="exportFieldGrid"></div></section><section class="export-preview-panel"><div class="export-preview-head"><div><h3>导出数据预览</h3><span>最多预览前 20 条，下载包含全部筛选记录。</span></div><span id="exportPreviewCount"></span></div><div class="export-preview-scroll" id="exportPreview"></div></section><div class="export-actions-v23"><p id="exportHint"></p><button id="downloadSelectedDataset">导出当前数据 CSV</button></div>`;page.appendChild(box);$('exportGroupFilter').onchange=render;$('selectAllExportFields').onclick=()=>{document.querySelectorAll('[data-export-field]').forEach(x=>x.checked=true);renderPreview()};$('clearExportFields').onclick=()=>{document.querySelectorAll('[data-export-field]').forEach(x=>x.checked=false);renderPreview()};$('downloadSelectedDataset').onclick=download;box.querySelectorAll('[data-export-dataset]').forEach(x=>x.onclick=()=>{active=x.dataset.exportDataset;render()})}
function renderGroupFilter(){const select=$('exportGroupFilter'),current=select.value||'all',available=new Set([...groups().groups,...assessmentRows().map(x=>x.group),...practiceRows().map(x=>x.group)]);select.innerHTML='<option value="all">全部分组</option>'+[...available].filter(Boolean).map(x=>`<option value="${safe(x)}">${safe(x)}</option>`).join('');select.value=[...available].includes(current)||current==='all'?current:'all'}
function renderFields(){const chosen=new Set(selectedFields().filter(key=>fields[active].some(([field])=>field===key)));$('exportFieldGrid').innerHTML=fields[active].map(([key,label])=>`<label class="export-field-option"><input type="checkbox" data-export-field="${key}" ${!chosen.size||chosen.has(key)?'checked':''}><span><b>${safe(label)}</b><span>${key}</span></span></label>`).join('');document.querySelectorAll('[data-export-field]').forEach(x=>x.onchange=renderPreview)}
function renderSummary(){const list=rows(),participants=new Set(list.map(x=>x.participant_id)),groupCount=new Set(list.map(x=>x.group)),extra=active==='assessment'?new Set(list.map(x=>x.wave)).size:list.reduce((a,b)=>a+(Number(b.minutes)||0),0);$('exportSummary').innerHTML=[[list.length,'筛选后记录'],[participants.size,'参与者'],[groupCount.size,'涉及分组'],[extra,active==='assessment'?'测评时间点':'累计分钟']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function renderPreview(){const list=rows(),selected=selectedFields();$('exportPreviewCount').textContent=`${list.length} 条记录 · ${selected.length} 个字段`;$('exportHint').textContent=`将导出“${datasets[active].label}”，分组：${$('exportGroupFilter').selectedOptions[0]?.textContent||'全部分组'}。`;if(!selected.length){$('exportPreview').innerHTML='<div class="export-preview-empty">请至少勾选一个导出字段。</div>';return}if(!list.length){$('exportPreview').innerHTML='<div class="export-preview-empty">当前筛选条件下暂无真实记录。</div>';return}const labels=Object.fromEntries(fields[active]);$('exportPreview').innerHTML=`<table class="export-preview-table"><thead><tr>${selected.map(x=>`<th>${safe(labels[x])}</th>`).join('')}</tr></thead><tbody>${list.slice(0,20).map(row=>`<tr>${selected.map(x=>`<td title="${safe(typeof row[x]==='object'?json(row[x]):row[x])}">${safe(typeof row[x]==='object'?json(row[x]):row[x])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function render(){if($('splitExportGroup'))return;buildPage();renderGroupFilter();document.querySelectorAll('[data-export-dataset]').forEach(x=>x.classList.toggle('active',x.dataset.exportDataset===active));renderFields();renderSummary();renderPreview()}
function csvCell(value){return'"'+String(value??'').replace(/"/g,'""')+'"'}function download(){const list=rows(),selected=selectedFields();if(!selected.length){alert('请至少选择一个导出字段。');return}if(!list.length){alert('当前筛选条件下没有可导出的记录。');return}const labels=Object.fromEntries(fields[active]),csv='\ufeff'+[selected.map(x=>labels[x]),...list.map(row=>selected.map(x=>typeof row[x]==='object'?json(row[x]):row[x]))].map(row=>row.map(csvCell).join(',')).join('\r\n'),group=$('exportGroupFilter').value==='all'?'all_groups':$('exportGroupFilter').value;downloadFile(`mied_${active}_${group}_${new Date().toISOString().slice(0,10)}.csv`,csv,'text/csv;charset=utf-8');addAdminActivity(`导出${datasets[active].label}：${list.length}条，${selected.length}字段`);saveAdmin()}
document.querySelectorAll('[data-admin-page="data"]').forEach(x=>{const icon=x.querySelector('i');if(icon)icon.textContent='出';for(const node of x.childNodes)if(node.nodeType===3)node.textContent='数据导出'});if(typeof adminTitles!=='undefined')adminTitles.data='数据导出';
const renderAdminDataBeforeExport=renderAdminData;renderAdminData=function(){try{renderAdminDataBeforeExport()}catch(e){}render()};const renderAdminPageBeforeExport=renderAdminPage;renderAdminPage=function(id){renderAdminPageBeforeExport(id);if(id==='data')render()};buildPage();render();document.documentElement.dataset.dataExportVersion='v23';
})();
