(()=>{
const KEY='mied_daily_tasks_v27',$=id=>document.getElementById(id),escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{"tasks":[]}');return{tasks:Array.isArray(x.tasks)?x.tasks:[]}}catch(e){return{tasks:[]}}}function write(x){localStorage.setItem(KEY,JSON.stringify(x))}function groupData(){try{return JSON.parse(localStorage.getItem('mied_participant_groups_v22')||'{}')}catch(e){return{}}}function allGroups(){const x=groupData();return x.groups?.length?x.groups:['待分组','演示组','干预A组','干预B组']}
function activeParticipant(){try{const r=JSON.parse(localStorage.getItem('mied_registration_v19')||'{}'),app=r.session&&r.applications?.find(x=>x.id===r.session.applicationId);return app?.participantId||'MIED-001'}catch(e){return'MIED-001'}}function participantGroup(){const pid=activeParticipant(),x=groupData();if(x.assignments?.[pid])return x.assignments[pid];try{return allParticipants().find(p=>p.id===pid)?.group||'演示组'}catch(e){return'演示组'}}function isoToday(){const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${d.getFullYear()}-${m}-${day}`}
function publishedFor(date=isoToday(),group=participantGroup()){return read().tasks.filter(x=>x.date===date&&(x.group==='all'||x.group===group)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt))[0]}
const previousTodayDaily=todayDaily;todayDaily=function(){const d=previousTodayDaily(),published=publishedFor();if(published&&Array.isArray(published.practices)&&published.practices.length){d.recommendedTitles=published.practices.slice(0,2);d.publishedTaskId=published.id;d.publishedTaskNote=published.note||''}return d};
function addQuickLogin(){const form=$('researchTeamLogin');if(!form||$('researchQuickLogin'))return;const button=document.createElement('button');button.type='button';button.id='researchQuickLogin';button.className='research-quick-login';button.innerHTML='一键登录检查后台<small>自动使用原型演示账号</small>';form.insertAdjacentElement('afterend',button);button.onclick=()=>{$('researchTeamUser').value='research_admin';$('researchTeamPassword').value='MIED2026';form.requestSubmit()}}
function ensureTaskTab(){const tabs=document.querySelector('#admin-content .content-tabs');if(!tabs)return;if(!tabs.querySelector('[data-content-kind="task"]'))tabs.insertAdjacentHTML('beforeend','<button data-content-kind="task">打卡任务</button>');tabs.querySelectorAll('[data-content-kind]').forEach(button=>button.onclick=()=>{activeContentKind=button.dataset.contentKind;tabs.querySelectorAll('[data-content-kind]').forEach(x=>x.classList.toggle('active',x===button));renderAdminContent()})}
function taskPanel(){const tasks=read().tasks,groups=allGroups(),options=practices.map(p=>`<option value="${escape(p.title)}">${escape(p.title)} · ${p.time}分钟</option>`).join('');return`<section class="task-publish-panel"><div class="task-publish-form"><label>发布日期<input id="taskPublishDate" type="date" value="${isoToday()}"></label><label>目标参与者分组<select id="taskPublishGroup"><option value="all">全部分组</option>${groups.map(g=>`<option value="${escape(g)}">${escape(g)}</option>`).join('')}</select></label><label>打卡练习 1<select id="taskPracticeOne">${options}</select></label><label>打卡练习 2<select id="taskPracticeTwo">${options}</select></label><label class="full">任务说明（选填）<textarea id="taskPublishNote" rows="2" placeholder="例如：今天从两项练习中各留出一点时间，完成任意一项后即可打卡。"></textarea></label><div class="task-publish-actions"><span>同一日期、同一分组再次发布时，新任务将覆盖参与者端当天推荐。</span><button id="publishDailyTask">发布每日打卡任务</button></div></div><article class="admin-panel"><div class="panel-head"><div><small>发布记录</small><h3>每日练习打卡任务</h3></div><span class="panel-tag">${tasks.length} 条</span></div><div class="published-task-list">${tasks.length?tasks.sort((a,b)=>b.date.localeCompare(a.date)||new Date(b.publishedAt)-new Date(a.publishedAt)).map(x=>`<div class="published-task-item"><time>${escape(x.date)}</time><div><b>${escape(x.group==='all'?'全部分组':x.group)} · ${x.practices.map(escape).join(' + ')}</b><span>${escape(x.note||'无额外说明')} · 发布于 ${new Date(x.publishedAt).toLocaleString('zh-CN')}</span></div><button data-revoke-task="${x.id}">撤回</button></div>`).join(''):'<div class="task-empty">尚未发布每日打卡任务。</div>'}</div></article></section>`}
const renderContentBeforeTasks=renderAdminContent;renderAdminContent=function(){ensureTaskTab();if(activeContentKind!=='task'){renderContentBeforeTasks();ensureTaskTab();return}const content=$('contentList');content.innerHTML=taskPanel();$('publishDailyTask').onclick=publishTask;content.querySelectorAll('[data-revoke-task]').forEach(x=>x.onclick=()=>{if(!confirm('确认撤回这条打卡任务？'))return;const data=read();data.tasks=data.tasks.filter(t=>t.id!==x.dataset.revokeTask);write(data);addAdminActivity('撤回每日打卡任务');saveAdmin();renderAdminContent()})};
function publishTask(){const date=$('taskPublishDate').value,group=$('taskPublishGroup').value,one=$('taskPracticeOne').value,two=$('taskPracticeTwo').value,note=$('taskPublishNote').value.trim();if(!date||!one||!two)return alert('请选择发布日期和两项练习。');if(one===two)return alert('请选择两项不同的练习。');const data=read(),task={id:`TASK-${Date.now()}`,date,group,practices:[one,two],note,publishedAt:new Date().toISOString()};data.tasks.push(task);write(data);addAdminActivity(`发布${date} ${group==='all'?'全部分组':group}打卡任务：${one}、${two}`);saveAdmin();renderAdminContent();toast('每日练习打卡任务已发布。');if(date===isoToday())try{renderTasks();renderPractices()}catch(e){}}
addQuickLogin();ensureTaskTab();const originalContentPage=renderAdminPage;renderAdminPage=function(id){originalContentPage(id);if(id==='content'){ensureTaskTab();renderAdminContent()}};document.documentElement.dataset.dailyTaskVersion='v27';
})();
